type AutoGenerated struct {
	Jsonrpc string `json:"jsonrpc"`
	ID      int    `json:"id"`
	Result  struct {
		Blockscore      string `json:"blockscore"`
		ExtraData       string `json:"extraData"`
		GasUsed         string `json:"gasUsed"`
		GovernanceData  string `json:"governanceData"`
		Hash            string `json:"hash"`
		LogsBloom       string `json:"logsBloom"`
		Number          string `json:"number"`
		ParentHash      string `json:"parentHash"`
		ReceiptsRoot    string `json:"receiptsRoot"`
		Reward          string `json:"reward"`
		Size            string `json:"size"`
		StateRoot       string `json:"stateRoot"`
		Timestamp       string `json:"timestamp"`
		TimestampFoS    string `json:"timestampFoS"`
		TotalBlockScore string `json:"totalBlockScore"`
		Transactions    []struct {
			BlockHash    string `json:"blockHash"`
			BlockNumber  string `json:"blockNumber"`
			From         string `json:"from"`
			Gas          string `json:"gas"`
			GasPrice     string `json:"gasPrice"`
			Hash         string `json:"hash"`
			Input        string `json:"input"`
			Nonce        string `json:"nonce"`
			SenderTxHash string `json:"senderTxHash"`
			Signatures   []struct {
				V string `json:"V"`
				R string `json:"R"`
				S string `json:"S"`
			} `json:"signatures"`
			To                 string `json:"to,omitempty"`
			TransactionIndex   string `json:"transactionIndex"`
			Type               string `json:"type"`
			TypeInt            int    `json:"typeInt"`
			Value              string `json:"value,omitempty"`
			FeePayer           string `json:"feePayer,omitempty"`
			FeePayerSignatures []struct {
				V string `json:"V"`
				R string `json:"R"`
				S string `json:"S"`
			} `json:"feePayerSignatures,omitempty"`
		} `json:"transactions"`
		TransactionsRoot string `json:"transactionsRoot"`
		VoteData         string `json:"voteData"`
	} `json:"result"`
}